config/routes.rb
YetiBarrage::Application.routes.draw do
  match 'yetis/map' => 'yetis#map'
  resources :yetis

  root to: "yetis#map"

end

app/models/yeti.rb
require 'htmlentities' 

class Yeti < ActiveRecord::Base
  attr_accessible :lat, :long, :name

  validates :name, { presence: true, length: { maximum: 100 } }
  validates :lat, { presence: true, numericality: { greater_than: -90, less_than: 90} }
  validates :long, { presence: true, numericality: { greater_than: -180, less_than: 180} }

  # Encode entities before validation so that the encoded string is still required to
  # be less than the maximum length.
  before_validation do
    self.name = HTMLEntities.new.encode(name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/yetis_controller.rb
class YetisController < ApplicationController
  # GET /yetis
  # GET /yetis.json
  def index
    @yetis = Yeti.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @yetis }
    end
  end

  # GET /yetis/map
  def map
    @google_maps_api_key = google_maps_api_key
  end

  # GET /yetis/new
  # GET /yetis/new.json
  def new
    @yeti = Yeti.new

    respond_to do |format|
      format.html # new.html.erb
      format.json # new.json.erb
      end
  end

  # GET /yetis/1/edit
  def edit
    @yeti = Yeti.find(params[:id])
  end

  # POST /yetis
  # POST /yetis.json
  def create
    @yeti = Yeti.new(params[:yeti])

    respond_to do |format|
      if @yeti.save
        format.html { redirect_to yetis_map_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /yetis/1
  # PUT /yetis/1.json
  def update
    @yeti = Yeti.find(params[:id])

    respond_to do |format|
      if @yeti.update_attributes(params[:yeti])
        format.html { redirect_to yetis_url }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /yetis/1
  # DELETE /yetis/1.json
  def destroy
    @yeti = Yeti.find(params[:id])
    @yeti.destroy

    respond_to do |format|
      format.html { redirect_to yetis_url }
    end
  end
  
  private
    def google_maps_api_key
      return ENV["google_maps_api_key"].strip
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yetis_helper.rb
module YetisHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="http://yeti-barrage.herokuapp.com"><h1>Yeti-Barrage</h1></a>
        <nav>
          <%= link_to "Map", root_path %>
          <%= link_to "Yetis", yetis_path %>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YetiBarrage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<% if action_name == "map" %>
  <script type="text/javascript"
    src="http://maps.googleapis.com/maps/api/js?key=<%= @google_maps_api_key %>&sensor=false"></script>
</head>
<body onload="map = new Map();map.initialize()">
<% else %>
</head>
<body>
<% end %>

<div class="container">
  <%= render 'layouts/nav' %>

  <%= yield %>
</div>

</body>
</html>

app/views/yetis/_form.html.erb
<%= form_for(@yeti) do |f| %>
  <% if @yeti.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yeti.errors.count, "error") %> prohibited this yeti from being saved:</h2>

      <ul>
      <% @yeti.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to 'Back', yetis_path, class: "btn" %>
  </div>
<% end %>

app/views/yetis/edit.html.erb
<h3>Edit a Yeti</h3>

<%= render 'form' %>

app/views/yetis/index.html.erb
<h4>A List</h4>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Long</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @yetis.each do |yeti| %>
    <tr>
      <td><%= yeti.name %></td>
      <td><%= yeti.lat %></td>
      <td><%= yeti.long %></td>
      <td><%= link_to 'Edit', edit_yeti_path(yeti), class: "btn btn-success" %></td>
      <td><%= link_to 'Destroy', yeti, method: :delete, class: "btn btn-danger" %></td>
    </tr>
<% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Yeti', new_yeti_path, class: "btn btn-primary" %>

app/views/yetis/map.html.erb
<div id="map_canvas" style="width:100%; height:100%;"></div>

app/views/yetis/new.html.erb
<h3>New yeti</h3>

<%= render 'form' %>

app/views/yetis/new.json.erb
{
  "html" : "<h3>New Yeti</h3><%= escape_javascript(render 'form.html') %>"
}

app/views/yetis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @yeti.name %>
</p>

<p>
  <b>Lat:</b>
  <%= @yeti.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @yeti.long %>
</p>


<%= link_to 'Edit', edit_yeti_path(@yeti), class: "btn btn-success" %> |
<%= link_to 'Back', yetis_path, class: "btn" %>